apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
  - name: my-nginx-1
    image: nginx:1.27
    env:
      - name: APP_NAME
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: APP_NAME
      - name: ENVIRONMENT
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: ENVIRONMENT
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: LOG_LEVEL
    ports:
    - containerPort: 81
